select distinct(client_sex) as '客户性别' from acct_wt_user_client_info;
select distinct(age_group) as '客户年龄段' from acct_wt_user_client_info;
select distinct(impression) as '客户印象' from acct_wt_user_account_impression;
select distinct(business_access) as '业务权限' from acct_wt_user_businesspermission;
select distinct(activity_level) as '活跃程度' from acct_wt_user_activity;
select distinct(open_time) as '开户时长' from acct_wt_user_client_info;
select distinct(branch_name) as '营业部' from acct_wt_user_client_info;
select distinct(account_status) as '交易账户状态' from acct_wt_user_client_info;
select distinct(last_week_most_income_stock) as '近一周收益最多的股票' from acct_wt_user_max_profit_stock;
select distinct(last_week_most_loss_stock) as '近一周亏损最多的股票' from acct_wt_user_max_profit_stock;
select distinct(last_year_stock_invest_cycle_preference) as '股票投资周期偏好（最近一年）' from acct_wt_user_stock_hold_line_type where interval_type=4;
select distinct(last_year_taste_industry_plate) as '兴趣行业板块（最近一年）' from acct_wt_user_interest_industry_block where interval_type=4;
select distinct(last_year_taste_concept_plate) as '兴趣概念板块（最近一年）' from acct_wt_user_interest_concept_block where interval_type=4;
select distinct(last_month_stock_market_value_preference) as '股票市值偏好（近一月）' from acct_wt_user_float_share_preference where interval_type=1;
select distinct(last_month_stock_price_preference) as '股票价格偏好（近一月）' from acct_wt_user_price_preference_1 where interval_type=1;
select distinct(last_month_stock_industry_preference) as '股票行业偏好（近一月）' from acct_wt_user_industry_preference where interval_type=1;
select distinct(stock_preference) as '偏好个股' from acct_wt_user_stock_preference;
select distinct(last_month_client_style) as '股票投资周期偏好（近一月）' from acct_wt_user_stock_hold_line_type where interval_type=1;
select distinct(last_three_month_client_style) as '股票投资周期偏好（近三月）' from acct_wt_user_stock_hold_line_type where interval_type=2;
select distinct(last_six_month_client_style) as '股票投资周期偏好（近半年）' from acct_wt_user_stock_hold_line_type where interval_type=3;
select distinct(last_year_adept_stock) as '擅长个股（最近一年）' from acct_wt_user_good_at_stock <- acct_wt_user_stock_hold_cycle_365, acct_wt_user_stock_hold_cycle_notend_365 where interval_type=4;
select distinct(last_month_lose_most) as '亏损最多股票（近一月）' from acct_wt_user_max_loss_stock where interval_type=1;
select distinct(last_three_month_lose_most) as '亏损最多股票（近三月）' from acct_wt_user_max_loss_stock where interval_type=2;
select distinct(last_six_month_lose_most) as '亏损最多股票（近半年）' from acct_wt_user_max_loss_stock where interval_type=3;
select distinct(last_year_lose_most) as '亏损最多股票（近一年）' from acct_wt_user_max_loss_stock where interval_type=4;
select distinct(client_asset_level) as '客户资产级别' from acct_wt_user_client_level;
select distinct(last_month_free_balance_level) as '闲置资金最小金额数量级（最近一月）' from acct_wt_user_min_fund_asset_leavel where interval_type=1;
select distinct(month_flush_stock) as '清仓股票（每月）' from acct_wt_user_month_stock_hold_cycle.stock_code;
select distinct(last_month_hold_longest) as '持仓最久股票（近一月）' from acct_wt_user_max_holddays_stock where interval_type=1;
select distinct(last_three_month_hold_longest) as '持仓最久股票（近三月）' from acct_wt_user_max_holddays_stock where interval_type=2;
select distinct(last_six_month_hold_longest) as '持仓最久股票（近半年）' from acct_wt_user_max_holddays_stock where interval_type=3;
select distinct(last_year_hold_longest) as '持仓最久股票（近一年）' from acct_wt_user_max_holddays_stock where interval_type=4;
select distinct(last_month_most_profit) as '净赚最多股票（近一月）' from acct_wt_user_max_profit_stock where interval_type=1;
select distinct(last_three_month_most_profit) as '净赚最多股票（近三月）' from acct_wt_user_max_profit_stock where interval_type=2;
select distinct(last_six_month_most_profit) as '净赚最多股票（近半年）' from acct_wt_user_max_profit_stock where interval_type=3;
select distinct(last_year_most_profit) as '净赚最多股票（近一年）' from acct_wt_user_max_profit_stock where interval_type=4;
select distinct(good_at_stock) as '擅长个股' from acct_wt_user_good_at_stock;
