select '所属地区' as name, count(residence) as tag_num, count(*) as total_num, (1-count(residence)/count(*)) as null_rate from acct_wt_user_client_info union
select '户籍地' as name, count(domicile) as tag_num, count(*) as total_num, (1-count(domicile)/count(*)) as null_rate from acct_wt_user_client_info union
select '股票佣金贡献' as name, count(stock_commission_offer) as tag_num, count(*) as total_num, (1-count(stock_commission_offer)/count(*)) as null_rate from acct_wt_user_day_commission_offer union
select '股票佣金贡献（近一月）' as name, count(total_stock_commission_offer) as tag_num, count(*) as total_num, (1-count(total_stock_commission_offer)/count(*)) as null_rate from acct_wt_user_total_commission_offer where interval_type=1 union
select '股票佣金贡献（近三月）' as name, count(total_stock_commission_offer) as tag_num, count(*) as total_num, (1-count(total_stock_commission_offer)/count(*)) as null_rate from acct_wt_user_total_commission_offer where interval_type=2 union
select '股票佣金贡献（近半年）' as name, count(total_stock_commission_offer) as tag_num, count(*) as total_num, (1-count(total_stock_commission_offer)/count(*)) as null_rate from acct_wt_user_total_commission_offer where interval_type=3 union
select '股票佣金贡献（近一年）' as name, count(total_stock_commission_offer) as tag_num, count(*) as total_num, (1-count(total_stock_commission_offer)/count(*)) as null_rate from acct_wt_user_total_commission_offer where interval_type=4 union
select '场内基金市值' as name, count(of_market_value) as tag_num, count(*) as total_num, (1-count(of_market_value)/count(*)) as null_rate from acct_wt_user_of_market_value union
select '日均场内基金市值（近一月）' as name, count(avg_of_market_value) as tag_num, count(*) as total_num, (1-count(avg_of_market_value)/count(*)) as null_rate from acct_wt_user_avg_of_market_value where interval_type=1 union
select '日均场内基金市值（近三月）' as name, count(avg_of_market_value) as tag_num, count(*) as total_num, (1-count(avg_of_market_value)/count(*)) as null_rate from acct_wt_user_avg_of_market_value where interval_type=2 union
select '日均场内基金市值（近半年）' as name, count(avg_of_market_value) as tag_num, count(*) as total_num, (1-count(avg_of_market_value)/count(*)) as null_rate from acct_wt_user_avg_of_market_value where interval_type=3 union
select '日均场内基金市值（近一年）' as name, count(avg_of_market_value) as tag_num, count(*) as total_num, (1-count(avg_of_market_value)/count(*)) as null_rate from acct_wt_user_avg_of_market_value where interval_type=4 union
select '场内基金佣金贡献' as name, count(of_commission_offer) as tag_num, count(*) as total_num, (1-count(of_commission_offer)/count(*)) as null_rate from acct_wt_user_day_commission_offer union
select '场内基金佣金贡献（近一月）' as name, count(total_of_commission_offer) as tag_num, count(*) as total_num, (1-count(total_of_commission_offer)/count(*)) as null_rate from acct_wt_user_total_commission_offer where interval_type=1 union
select '场内基金佣金贡献（近三月）' as name, count(total_of_commission_offer) as tag_num, count(*) as total_num, (1-count(total_of_commission_offer)/count(*)) as null_rate from acct_wt_user_total_commission_offer where interval_type=2 union
select '场内基金佣金贡献（近半年）' as name, count(total_of_commission_offer) as tag_num, count(*) as total_num, (1-count(total_of_commission_offer)/count(*)) as null_rate from acct_wt_user_total_commission_offer where interval_type=3 union
select '场内基金佣金贡献（近一年）' as name, count(total_of_commission_offer) as tag_num, count(*) as total_num, (1-count(total_of_commission_offer)/count(*)) as null_rate from acct_wt_user_total_commission_offer where interval_type=4 union
select '债券佣金贡献' as name, count(bond_commission_offer) as tag_num, count(*) as total_num, (1-count(bond_commission_offer)/count(*)) as null_rate from acct_wt_user_day_commission_offer union
select '债券佣金贡献（近一月）' as name, count(total_bond_commission_offer) as tag_num, count(*) as total_num, (1-count(total_bond_commission_offer)/count(*)) as null_rate from acct_wt_user_total_commission_offer where interval_type=1 union
select '债券佣金贡献（近三月）' as name, count(total_bond_commission_offer) as tag_num, count(*) as total_num, (1-count(total_bond_commission_offer)/count(*)) as null_rate from acct_wt_user_total_commission_offer where interval_type=2 union
select '债券佣金贡献（近半年）' as name, count(total_bond_commission_offer) as tag_num, count(*) as total_num, (1-count(total_bond_commission_offer)/count(*)) as null_rate from acct_wt_user_total_commission_offer where interval_type=3 union
select '债券佣金贡献（近一年）' as name, count(total_bond_commission_offer) as tag_num, count(*) as total_num, (1-count(total_bond_commission_offer)/count(*)) as null_rate from acct_wt_user_total_commission_offer where interval_type=4 union
select '其他市值' as name, count(other_market_value) as tag_num, count(*) as total_num, (1-count(other_market_value)/count(*)) as null_rate from acct_wt_user_other_market_value union
select '日均其他市值（近一月）' as name, count(avg_market_value) as tag_num, count(*) as total_num, (1-count(avg_market_value)/count(*)) as null_rate from acct_wt_user_avg_other_market_value where interval_type=1 union
select '日均其他市值（近三月）' as name, count(avg_market_value) as tag_num, count(*) as total_num, (1-count(avg_market_value)/count(*)) as null_rate from acct_wt_user_avg_other_market_value where interval_type=2 union
select '日均其他市值（近半年）' as name, count(avg_market_value) as tag_num, count(*) as total_num, (1-count(avg_market_value)/count(*)) as null_rate from acct_wt_user_avg_other_market_value where interval_type=3 union
select '日均其他市值（近一年）' as name, count(avg_market_value) as tag_num, count(*) as total_num, (1-count(avg_market_value)/count(*)) as null_rate from acct_wt_user_avg_other_market_value where interval_type=4 union
select '其他交易金额' as name, count(other_trade_balance) as tag_num, count(*) as total_num, (1-count(other_trade_balance)/count(*)) as null_rate from acct_wt_user_other_trade_balance union
select '日均其他交易金额（近一月）' as name, count(avg_trade_balance) as tag_num, count(*) as total_num, (1-count(avg_trade_balance)/count(*)) as null_rate from acct_wt_user_avg_other_trade_balance where interval_type=1 union
select '日均其他交易金额（近三月）' as name, count(avg_trade_balance) as tag_num, count(*) as total_num, (1-count(avg_trade_balance)/count(*)) as null_rate from acct_wt_user_avg_other_trade_balance where interval_type=2 union
select '日均其他交易金额（近半年）' as name, count(avg_trade_balance) as tag_num, count(*) as total_num, (1-count(avg_trade_balance)/count(*)) as null_rate from acct_wt_user_avg_other_trade_balance where interval_type=3 union
select '日均其他交易金额（近一年）' as name, count(avg_trade_balance) as tag_num, count(*) as total_num, (1-count(avg_trade_balance)/count(*)) as null_rate from acct_wt_user_avg_other_trade_balance where interval_type=4 union
select '其他交易次数（近一月）' as name, count(total_trade_times) as tag_num, count(*) as total_num, (1-count(total_trade_times)/count(*)) as null_rate from acct_wt_user_total_other_trade_times where interval_type=1 union
select '其他交易次数（近三月）' as name, count(total_trade_times) as tag_num, count(*) as total_num, (1-count(total_trade_times)/count(*)) as null_rate from acct_wt_user_total_other_trade_times where interval_type=2 union
select '其他交易次数（近半年）' as name, count(total_trade_times) as tag_num, count(*) as total_num, (1-count(total_trade_times)/count(*)) as null_rate from acct_wt_user_total_other_trade_times where interval_type=3 union
select '其他交易次数（近一年）' as name, count(total_trade_times) as tag_num, count(*) as total_num, (1-count(total_trade_times)/count(*)) as null_rate from acct_wt_user_total_other_trade_times where interval_type=4 union
select '其他佣金贡献' as name, count(other_commission_offer) as tag_num, count(*) as total_num, (1-count(other_commission_offer)/count(*)) as null_rate from acct_wt_user_day_commission_offer union
select '其他佣金贡献（近一月）' as name, count(total_other_commission_offer) as tag_num, count(*) as total_num, (1-count(total_other_commission_offer)/count(*)) as null_rate from acct_wt_user_total_commission_offer where interval_type=1 union
select '其他佣金贡献（近三月）' as name, count(total_other_commission_offer) as tag_num, count(*) as total_num, (1-count(total_other_commission_offer)/count(*)) as null_rate from acct_wt_user_total_commission_offer where interval_type=2 union
select '其他佣金贡献（近半年）' as name, count(total_other_commission_offer) as tag_num, count(*) as total_num, (1-count(total_other_commission_offer)/count(*)) as null_rate from acct_wt_user_total_commission_offer where interval_type=3 union
select '其他佣金贡献（近一年）' as name, count(total_other_commission_offer) as tag_num, count(*) as total_num, (1-count(total_other_commission_offer)/count(*)) as null_rate from acct_wt_user_total_commission_offer where interval_type=4 union
select '场外开基总市值' as name, count(otc_open_market_value) as tag_num, count(*) as total_num, (1-count(otc_open_market_value)/count(*)) as null_rate from acct_wt_user_outside_prod_market_value union
select '日均场外开基总市值（近一月）' as name, count(avg_otc_open_market_value) as tag_num, count(*) as total_num, (1-count(avg_otc_open_market_value)/count(*)) as null_rate from acct_wt_user_avg_outside_prod_market_value where interval_type=1 union
select '日均场外开基总市值（近三月）' as name, count(avg_otc_open_market_value) as tag_num, count(*) as total_num, (1-count(avg_otc_open_market_value)/count(*)) as null_rate from acct_wt_user_avg_outside_prod_market_value where interval_type=2 union
select '日均场外开基总市值（近半年）' as name, count(avg_otc_open_market_value) as tag_num, count(*) as total_num, (1-count(avg_otc_open_market_value)/count(*)) as null_rate from acct_wt_user_avg_outside_prod_market_value where interval_type=3 union
select '日均场外开基总市值（近一年）' as name, count(avg_otc_open_market_value) as tag_num, count(*) as total_num, (1-count(avg_otc_open_market_value)/count(*)) as null_rate from acct_wt_user_avg_outside_prod_market_value where interval_type=4 union
select '场外开基认申购金额' as name, count(otc_open_sub_app_balance) as tag_num, count(*) as total_num, (1-count(otc_open_sub_app_balance)/count(*)) as null_rate from acct_wt_user_outside_prod_redeem_balance union
select '场外开基认申购金额（近一月）' as name, count(total_otc_open_sub_app_balance) as tag_num, count(*) as total_num, (1-count(total_otc_open_sub_app_balance)/count(*)) as null_rate from acct_wt_user_outside_prod_total_redeem_balance where interval_type=1 union
select '场外开基认申购金额（近三月）' as name, count(total_otc_open_sub_app_balance) as tag_num, count(*) as total_num, (1-count(total_otc_open_sub_app_balance)/count(*)) as null_rate from acct_wt_user_outside_prod_total_redeem_balance where interval_type=2 union
select '场外开基认申购金额（近半年）' as name, count(total_otc_open_sub_app_balance) as tag_num, count(*) as total_num, (1-count(total_otc_open_sub_app_balance)/count(*)) as null_rate from acct_wt_user_outside_prod_total_redeem_balance where interval_type=3 union
select '场外开基认申购金额（近一年）' as name, count(total_otc_open_sub_app_balance) as tag_num, count(*) as total_num, (1-count(total_otc_open_sub_app_balance)/count(*)) as null_rate from acct_wt_user_outside_prod_total_redeem_balance where interval_type=4 union
select '场外开基赎回金额' as name, count(otc_open_redeem_balance) as tag_num, count(*) as total_num, (1-count(otc_open_redeem_balance)/count(*)) as null_rate from acct_wt_user_outside_prod_redeem_balance union
select '场外开基赎回金额（近一月）' as name, count(total_otc_open_redeem_balance) as tag_num, count(*) as total_num, (1-count(total_otc_open_redeem_balance)/count(*)) as null_rate from acct_wt_user_outside_prod_total_redeem_balance where interval_type=1 union
select '场外开基赎回金额（近三月）' as name, count(total_otc_open_redeem_balance) as tag_num, count(*) as total_num, (1-count(total_otc_open_redeem_balance)/count(*)) as null_rate from acct_wt_user_outside_prod_total_redeem_balance where interval_type=2 union
select '场外开基赎回金额（近半年）' as name, count(total_otc_open_redeem_balance) as tag_num, count(*) as total_num, (1-count(total_otc_open_redeem_balance)/count(*)) as null_rate from acct_wt_user_outside_prod_total_redeem_balance where interval_type=3 union
select '场外开基赎回金额（近一年）' as name, count(total_otc_open_redeem_balance) as tag_num, count(*) as total_num, (1-count(total_otc_open_redeem_balance)/count(*)) as null_rate from acct_wt_user_outside_prod_total_redeem_balance where interval_type=4 union
select '炎黄汇利市值' as name, count(c90005_market_value) as tag_num, count(*) as total_num, (1-count(c90005_market_value)/count(*)) as null_rate from acct_wt_user_outside_prod_market_value union
select '日均炎黄汇利市值（近一月）' as name, count(avg_c90005_market_value) as tag_num, count(*) as total_num, (1-count(avg_c90005_market_value)/count(*)) as null_rate from acct_wt_user_avg_outside_prod_market_value where interval_type=1 union
select '日均炎黄汇利市值（近三月）' as name, count(avg_c90006_market_value) as tag_num, count(*) as total_num, (1-count(avg_c90006_market_value)/count(*)) as null_rate from acct_wt_user_avg_outside_prod_market_value where interval_type=2 union
select '日均炎黄汇利市值（近半年）' as name, count(avg_c90007_market_value) as tag_num, count(*) as total_num, (1-count(avg_c90007_market_value)/count(*)) as null_rate from acct_wt_user_avg_outside_prod_market_value where interval_type=3 union
select '日均炎黄汇利市值（近一年）' as name, count(avg_c90008_market_value) as tag_num, count(*) as total_num, (1-count(avg_c90008_market_value)/count(*)) as null_rate from acct_wt_user_avg_outside_prod_market_value where interval_type=4 union
select '资管产品市值' as name, count(assetmg_market_value) as tag_num, count(*) as total_num, (1-count(assetmg_market_value)/count(*)) as null_rate from acct_wt_user_outside_prod_market_value union
select '日均资管产品市值（近一月）' as name, count(avg_assetmg_market_value) as tag_num, count(*) as total_num, (1-count(avg_assetmg_market_value)/count(*)) as null_rate from acct_wt_user_avg_outside_prod_market_value where interval_type=1 union
select '日均资管产品市值（近三月）' as name, count(avg_assetmg_market_value) as tag_num, count(*) as total_num, (1-count(avg_assetmg_market_value)/count(*)) as null_rate from acct_wt_user_avg_outside_prod_market_value where interval_type=2 union
select '日均资管产品市值（近半年）' as name, count(avg_assetmg_market_value) as tag_num, count(*) as total_num, (1-count(avg_assetmg_market_value)/count(*)) as null_rate from acct_wt_user_avg_outside_prod_market_value where interval_type=3 union
select '日均资管产品市值（近一年）' as name, count(avg_assetmg_market_value) as tag_num, count(*) as total_num, (1-count(avg_assetmg_market_value)/count(*)) as null_rate from acct_wt_user_avg_outside_prod_market_value where interval_type=4 union
select '资管产品认申购金额' as name, count(assetmg_sub_app_balance) as tag_num, count(*) as total_num, (1-count(assetmg_sub_app_balance)/count(*)) as null_rate from acct_wt_user_outside_prod_redeem_balance union
select '资管产品认申购金额（近一月）' as name, count(total_assetmg_sub_app_balance) as tag_num, count(*) as total_num, (1-count(total_assetmg_sub_app_balance)/count(*)) as null_rate from acct_wt_user_outside_prod_total_redeem_balance where interval_type=1 union
select '资管产品认申购金额（近三月）' as name, count(total_assetmg_sub_app_balance) as tag_num, count(*) as total_num, (1-count(total_assetmg_sub_app_balance)/count(*)) as null_rate from acct_wt_user_outside_prod_total_redeem_balance where interval_type=2 union
select '资管产品认申购金额（近半年）' as name, count(total_assetmg_sub_app_balance) as tag_num, count(*) as total_num, (1-count(total_assetmg_sub_app_balance)/count(*)) as null_rate from acct_wt_user_outside_prod_total_redeem_balance where interval_type=3 union
select '资管产品认申购金额（近一年）' as name, count(total_assetmg_sub_app_balance) as tag_num, count(*) as total_num, (1-count(total_assetmg_sub_app_balance)/count(*)) as null_rate from acct_wt_user_outside_prod_total_redeem_balance where interval_type=4 union
select '资管产品赎回金额' as name, count(assetmg_redeem_balance) as tag_num, count(*) as total_num, (1-count(assetmg_redeem_balance)/count(*)) as null_rate from acct_wt_user_outside_prod_redeem_balance union
select '资管产品赎回金额（近一月）' as name, count(total_assetmg_redeem_balance) as tag_num, count(*) as total_num, (1-count(total_assetmg_redeem_balance)/count(*)) as null_rate from acct_wt_user_outside_prod_total_redeem_balance where interval_type=1 union
select '资管产品赎回金额（近三月）' as name, count(total_assetmg_redeem_balance) as tag_num, count(*) as total_num, (1-count(total_assetmg_redeem_balance)/count(*)) as null_rate from acct_wt_user_outside_prod_total_redeem_balance where interval_type=2 union
select '资管产品赎回金额（近半年）' as name, count(total_assetmg_redeem_balance) as tag_num, count(*) as total_num, (1-count(total_assetmg_redeem_balance)/count(*)) as null_rate from acct_wt_user_outside_prod_total_redeem_balance where interval_type=3 union
select '资管产品赎回金额（近一年）' as name, count(total_assetmg_redeem_balance) as tag_num, count(*) as total_num, (1-count(total_assetmg_redeem_balance)/count(*)) as null_rate from acct_wt_user_outside_prod_total_redeem_balance where interval_type=4 union
select '信用账户佣金贡献' as name, count(commission_offer) as tag_num, count(*) as total_num, (1-count(commission_offer)/count(*)) as null_rate from acct_wt_user_daily_credit_sum_deliver union
select '信用账户佣金贡献（近一月）' as name, count(commission_offer) as tag_num, count(*) as total_num, (1-count(commission_offer)/count(*)) as null_rate from acct_wt_user_credit_sum_deliver where interval_type=1 union
select '信用账户佣金贡献（近三月）' as name, count(commission_offer) as tag_num, count(*) as total_num, (1-count(commission_offer)/count(*)) as null_rate from acct_wt_user_credit_sum_deliver where interval_type=2 union
select '信用账户佣金贡献（近半年）' as name, count(commission_offer) as tag_num, count(*) as total_num, (1-count(commission_offer)/count(*)) as null_rate from acct_wt_user_credit_sum_deliver where interval_type=3 union
select '信用账户佣金贡献（近一年）' as name, count(commission_offer) as tag_num, count(*) as total_num, (1-count(commission_offer)/count(*)) as null_rate from acct_wt_user_credit_sum_deliver where interval_type=4 union
select '信用账户利息贡献' as name, count(interest_offer) as tag_num, count(*) as total_num, (1-count(interest_offer)/count(*)) as null_rate from acct_wt_user_daily_credit_asset_details union
select '信用账户利息贡献（近一月）' as name, count(interest_offer) as tag_num, count(*) as total_num, (1-count(interest_offer)/count(*)) as null_rate from acct_wt_user_credit_asset_details where interval_type=1 union
select '信用账户利息贡献（近三月）' as name, count(interest_offer) as tag_num, count(*) as total_num, (1-count(interest_offer)/count(*)) as null_rate from acct_wt_user_credit_asset_details where interval_type=2 union
select '信用账户利息贡献（近半年）' as name, count(interest_offer) as tag_num, count(*) as total_num, (1-count(interest_offer)/count(*)) as null_rate from acct_wt_user_credit_asset_details where interval_type=3 union
select '信用账户利息贡献（近一年）' as name, count(interest_offer) as tag_num, count(*) as total_num, (1-count(interest_offer)/count(*)) as null_rate from acct_wt_user_credit_asset_details where interval_type=4 union
select '信用账户普通交易次数' as name, count(credit_assure_trade_times) as tag_num, count(*) as total_num, (1-count(credit_assure_trade_times)/count(*)) as null_rate from acct_wt_user_daily_credit_sum_deliver union
select '信用账户普通交易次数（近一月）' as name, count(credit_assure_trade_times) as tag_num, count(*) as total_num, (1-count(credit_assure_trade_times)/count(*)) as null_rate from acct_wt_user_credit_sum_deliver where interval_type=1 union
select '信用账户普通交易次数（近三月）' as name, count(credit_assure_trade_times) as tag_num, count(*) as total_num, (1-count(credit_assure_trade_times)/count(*)) as null_rate from acct_wt_user_credit_sum_deliver where interval_type=2 union
select '信用账户普通交易次数（近半年）' as name, count(credit_assure_trade_times) as tag_num, count(*) as total_num, (1-count(credit_assure_trade_times)/count(*)) as null_rate from acct_wt_user_credit_sum_deliver where interval_type=3 union
select '信用账户普通交易次数（近一年）' as name, count(credit_assure_trade_times) as tag_num, count(*) as total_num, (1-count(credit_assure_trade_times)/count(*)) as null_rate from acct_wt_user_credit_sum_deliver where interval_type=4 union
select '融资融券交易次数' as name, count(credit_trade_times) as tag_num, count(*) as total_num, (1-count(credit_trade_times)/count(*)) as null_rate from acct_wt_user_daily_credit_sum_deliver union
select '融资融券交易次数（近一月）' as name, count(credit_trade_times) as tag_num, count(*) as total_num, (1-count(credit_trade_times)/count(*)) as null_rate from acct_wt_user_credit_sum_deliver where interval_type=1 union
select '融资融券交易次数（近三月）' as name, count(credit_trade_times) as tag_num, count(*) as total_num, (1-count(credit_trade_times)/count(*)) as null_rate from acct_wt_user_credit_sum_deliver where interval_type=2 union
select '融资融券交易次数（近半年）' as name, count(credit_trade_times) as tag_num, count(*) as total_num, (1-count(credit_trade_times)/count(*)) as null_rate from acct_wt_user_credit_sum_deliver where interval_type=3 union
select '融资融券交易次数（近一年）' as name, count(credit_trade_times) as tag_num, count(*) as total_num, (1-count(credit_trade_times)/count(*)) as null_rate from acct_wt_user_credit_sum_deliver where interval_type=4 union
select '信用账户普通交易金额' as name, count(credit_assure_trade_balance) as tag_num, count(*) as total_num, (1-count(credit_assure_trade_balance)/count(*)) as null_rate from acct_wt_user_daily_credit_sum_deliver union
select '日均信用账户普通交易金额（近一月）' as name, count(credit_avg_assure_trade_balance) as tag_num, count(*) as total_num, (1-count(credit_avg_assure_trade_balance)/count(*)) as null_rate from acct_wt_user_credit_sum_deliver where interval_type=1 union
select '日均信用账户普通交易金额（近三月）' as name, count(credit_avg_assure_trade_balance) as tag_num, count(*) as total_num, (1-count(credit_avg_assure_trade_balance)/count(*)) as null_rate from acct_wt_user_credit_sum_deliver where interval_type=2 union
select '日均信用账户普通交易金额（近半年）' as name, count(credit_avg_assure_trade_balance) as tag_num, count(*) as total_num, (1-count(credit_avg_assure_trade_balance)/count(*)) as null_rate from acct_wt_user_credit_sum_deliver where interval_type=3 union
select '日均信用账户普通交易金额（近一年）' as name, count(credit_avg_assure_trade_balance) as tag_num, count(*) as total_num, (1-count(credit_avg_assure_trade_balance)/count(*)) as null_rate from acct_wt_user_credit_sum_deliver where interval_type=4 union
select '融资融券交易金额' as name, count(credit_trade_balance) as tag_num, count(*) as total_num, (1-count(credit_trade_balance)/count(*)) as null_rate from acct_wt_user_daily_credit_sum_deliver union
select '日均融资融券交易金额（近一月）' as name, count(credit_avg_trade_balance) as tag_num, count(*) as total_num, (1-count(credit_avg_trade_balance)/count(*)) as null_rate from acct_wt_user_credit_sum_deliver where interval_type=1 union
select '日均融资融券交易金额（近三月）' as name, count(credit_avg_trade_balance) as tag_num, count(*) as total_num, (1-count(credit_avg_trade_balance)/count(*)) as null_rate from acct_wt_user_credit_sum_deliver where interval_type=2 union
select '日均融资融券交易金额（近半年）' as name, count(credit_avg_trade_balance) as tag_num, count(*) as total_num, (1-count(credit_avg_trade_balance)/count(*)) as null_rate from acct_wt_user_credit_sum_deliver where interval_type=3 union
select '日均融资融券交易金额（近一年）' as name, count(credit_avg_trade_balance) as tag_num, count(*) as total_num, (1-count(credit_avg_trade_balance)/count(*)) as null_rate from acct_wt_user_credit_sum_deliver where interval_type=4 union
select '触碰平仓线次数（近一月）' as name, count(hit_flat_line_count) as tag_num, count(*) as total_num, (1-count(hit_flat_line_count)/count(*)) as null_rate from acct_wt_user_credit_hit_flat_line_count where interval_type=1 union
select '触碰平仓线次数（近三月）' as name, count(hit_flat_line_count) as tag_num, count(*) as total_num, (1-count(hit_flat_line_count)/count(*)) as null_rate from acct_wt_user_credit_hit_flat_line_count where interval_type=2 union
select '触碰平仓线次数（近半年）' as name, count(hit_flat_line_count) as tag_num, count(*) as total_num, (1-count(hit_flat_line_count)/count(*)) as null_rate from acct_wt_user_credit_hit_flat_line_count where interval_type=3 union
select '触碰平仓线次数（近一年）' as name, count(hit_flat_line_count) as tag_num, count(*) as total_num, (1-count(hit_flat_line_count)/count(*)) as null_rate from acct_wt_user_credit_hit_flat_line_count where interval_type=4 union
select '期权佣金贡献' as name, count(opt_commission_offer) as tag_num, count(*) as total_num, (1-count(opt_commission_offer)/count(*)) as null_rate from acct_wt_user_opt_commission_offer union
select '期权佣金贡献（近一月）' as name, count(total_opt_commission_offer) as tag_num, count(*) as total_num, (1-count(total_opt_commission_offer)/count(*)) as null_rate from acct_wt_user_total_opt_commission_offer where interval_type=1 union
select '期权佣金贡献（近三月）' as name, count(total_opt_commission_offer) as tag_num, count(*) as total_num, (1-count(total_opt_commission_offer)/count(*)) as null_rate from acct_wt_user_total_opt_commission_offer where interval_type=2 union
select '期权佣金贡献（近半年）' as name, count(total_opt_commission_offer) as tag_num, count(*) as total_num, (1-count(total_opt_commission_offer)/count(*)) as null_rate from acct_wt_user_total_opt_commission_offer where interval_type=3 union
select '期权佣金贡献（近一年）' as name, count(total_opt_commission_offer) as tag_num, count(*) as total_num, (1-count(total_opt_commission_offer)/count(*)) as null_rate from acct_wt_user_total_opt_commission_offer where interval_type=4 union
select '日均资金余额（近一月）' as name, count(avg_current_balance) as tag_num, count(*) as total_num, (1-count(avg_current_balance)/count(*)) as null_rate from acct_wt_user_day_current_balance where interval_type=1 union
select '日均资金余额（近三月）' as name, count(avg_current_balance) as tag_num, count(*) as total_num, (1-count(avg_current_balance)/count(*)) as null_rate from acct_wt_user_day_current_balance where interval_type=2 union
select '日均资金余额（近半年）' as name, count(avg_current_balance) as tag_num, count(*) as total_num, (1-count(avg_current_balance)/count(*)) as null_rate from acct_wt_user_day_current_balance where interval_type=3 union
select '日均资金余额（近一年）' as name, count(avg_current_balance) as tag_num, count(*) as total_num, (1-count(avg_current_balance)/count(*)) as null_rate from acct_wt_user_day_current_balance where interval_type=4 union
select '持仓市值峰值（近一月）' as name, count(max_current_balance) as tag_num, count(*) as total_num, (1-count(max_current_balance)/count(*)) as null_rate from acct_wt_user_day_current_balance where interval_type=1 union
select '持仓市值峰值（近三月）' as name, count(max_current_balance) as tag_num, count(*) as total_num, (1-count(max_current_balance)/count(*)) as null_rate from acct_wt_user_day_current_balance where interval_type=2 union
select '持仓市值峰值（近半年）' as name, count(max_current_balance) as tag_num, count(*) as total_num, (1-count(max_current_balance)/count(*)) as null_rate from acct_wt_user_day_current_balance where interval_type=3 union
select '持仓市值峰值（近一年）' as name, count(max_current_balance) as tag_num, count(*) as total_num, (1-count(max_current_balance)/count(*)) as null_rate from acct_wt_user_day_current_balance where interval_type=4 union
select '持仓市值谷值（近一月）' as name, count(min_current_balance) as tag_num, count(*) as total_num, (1-count(min_current_balance)/count(*)) as null_rate from acct_wt_user_day_current_balance where interval_type=1 union
select '持仓市值谷值（近三月）' as name, count(min_current_balance) as tag_num, count(*) as total_num, (1-count(min_current_balance)/count(*)) as null_rate from acct_wt_user_day_current_balance where interval_type=2 union
select '持仓市值谷值（近半年）' as name, count(min_current_balance) as tag_num, count(*) as total_num, (1-count(min_current_balance)/count(*)) as null_rate from acct_wt_user_day_current_balance where interval_type=3 union
select '持仓市值谷值（近一年）' as name, count(min_current_balance) as tag_num, count(*) as total_num, (1-count(min_current_balance)/count(*)) as null_rate from acct_wt_user_day_current_balance where interval_type=4 union
select '客户总资产' as name, count(client_total_asset) as tag_num, count(*) as total_num, (1-count(client_total_asset)/count(*)) as null_rate from acct_wt_user_client_total_asset union
select '日均客户总资产（近一月）' as name, count(client_avg_total_asset) as tag_num, count(*) as total_num, (1-count(client_avg_total_asset)/count(*)) as null_rate from acct_wt_user_client_avg_total_asset where interval_type=1 union
select '日均客户总资产（近三月）' as name, count(client_avg_total_asset) as tag_num, count(*) as total_num, (1-count(client_avg_total_asset)/count(*)) as null_rate from acct_wt_user_client_avg_total_asset where interval_type=2 union
select '日均客户总资产（近半年）' as name, count(client_avg_total_asset) as tag_num, count(*) as total_num, (1-count(client_avg_total_asset)/count(*)) as null_rate from acct_wt_user_client_avg_total_asset where interval_type=3 union
select '日均客户总资产（近一年）' as name, count(client_avg_total_asset) as tag_num, count(*) as total_num, (1-count(client_avg_total_asset)/count(*)) as null_rate from acct_wt_user_client_avg_total_asset where interval_type=4 union
select '客户佣金贡献' as name, count(client_commission_offer) as tag_num, count(*) as total_num, (1-count(client_commission_offer)/count(*)) as null_rate from acct_wt_user_client_commission_offer union
select '客户佣金贡献（近一月）' as name, count(client_total_commission_offer) as tag_num, count(*) as total_num, (1-count(client_total_commission_offer)/count(*)) as null_rate from acct_wt_user_client_total_commission_offer where interval_type=1 union
select '客户佣金贡献（近三月）' as name, count(client_total_commission_offer) as tag_num, count(*) as total_num, (1-count(client_total_commission_offer)/count(*)) as null_rate from acct_wt_user_client_total_commission_offer where interval_type=2 union
select '客户佣金贡献（近半年）' as name, count(client_total_commission_offer) as tag_num, count(*) as total_num, (1-count(client_total_commission_offer)/count(*)) as null_rate from acct_wt_user_client_total_commission_offer where interval_type=3 union
select '客户佣金贡献（近一年）' as name, count(client_total_commission_offer) as tag_num, count(*) as total_num, (1-count(client_total_commission_offer)/count(*)) as null_rate from acct_wt_user_client_total_commission_offer where interval_type=4 union
select '客户总持仓市值' as name, count(client_market_value) as tag_num, count(*) as total_num, (1-count(client_market_value)/count(*)) as null_rate from acct_wt_user_client_total_asset union
select '日均客户总持仓市值（近一月）' as name, count(client_avg_market_value) as tag_num, count(*) as total_num, (1-count(client_avg_market_value)/count(*)) as null_rate from acct_wt_user_client_avg_total_asset where interval_type=1 union
select '日均客户总持仓市值（近三月）' as name, count(client_avg_market_value) as tag_num, count(*) as total_num, (1-count(client_avg_market_value)/count(*)) as null_rate from acct_wt_user_client_avg_total_asset where interval_type=2 union
select '日均客户总持仓市值（近半年）' as name, count(client_avg_market_value) as tag_num, count(*) as total_num, (1-count(client_avg_market_value)/count(*)) as null_rate from acct_wt_user_client_avg_total_asset where interval_type=3 union
select '日均客户总持仓市值（近一年）' as name, count(client_avg_market_value) as tag_num, count(*) as total_num, (1-count(client_avg_market_value)/count(*)) as null_rate from acct_wt_user_client_avg_total_asset where interval_type=4 union
select '客户交易次数' as name, count(client_trade_times) as tag_num, count(*) as total_num, (1-count(client_trade_times)/count(*)) as null_rate from acct_wt_user_client_trade_times union
select '客户交易次数（近一月）' as name, count(client_trade_times) as tag_num, count(*) as total_num, (1-count(client_trade_times)/count(*)) as null_rate from acct_wt_user_client_total_trade_times where interval_type=1 union
select '客户交易次数（近三月）' as name, count(client_trade_times) as tag_num, count(*) as total_num, (1-count(client_trade_times)/count(*)) as null_rate from acct_wt_user_client_total_trade_times where interval_type=2 union
select '客户交易次数（近半年）' as name, count(client_trade_times) as tag_num, count(*) as total_num, (1-count(client_trade_times)/count(*)) as null_rate from acct_wt_user_client_total_trade_times where interval_type=3 union
select '客户交易次数（近一年）' as name, count(client_trade_times) as tag_num, count(*) as total_num, (1-count(client_trade_times)/count(*)) as null_rate from acct_wt_user_client_total_trade_times where interval_type=4 union
select '客户交易金额' as name, count(client_trade_balance) as tag_num, count(*) as total_num, (1-count(client_trade_balance)/count(*)) as null_rate from acct_wt_user_client_trade_times union
select '客户交易金额（近一月）' as name, count(client_trade_balance) as tag_num, count(*) as total_num, (1-count(client_trade_balance)/count(*)) as null_rate from acct_wt_user_client_total_trade_times where interval_type=1 union
select '客户交易金额（近三月）' as name, count(client_trade_balance) as tag_num, count(*) as total_num, (1-count(client_trade_balance)/count(*)) as null_rate from acct_wt_user_client_total_trade_times where interval_type=2 union
select '客户交易金额（近半年）' as name, count(client_trade_balance) as tag_num, count(*) as total_num, (1-count(client_trade_balance)/count(*)) as null_rate from acct_wt_user_client_total_trade_times where interval_type=3 union
select '客户交易金额（近一年）' as name, count(client_trade_balance) as tag_num, count(*) as total_num, (1-count(client_trade_balance)/count(*)) as null_rate from acct_wt_user_client_total_trade_times where interval_type=4 union
select '客户盈亏金额' as name, count(client_income) as tag_num, count(*) as total_num, (1-count(client_income)/count(*)) as null_rate from acct_wt_user_client_daily_income union
select '客户盈亏金额（近一月）' as name, count(client_income) as tag_num, count(*) as total_num, (1-count(client_income)/count(*)) as null_rate from acct_wt_user_client_income where interval_type=1 union
select '客户盈亏金额（近三月）' as name, count(client_income) as tag_num, count(*) as total_num, (1-count(client_income)/count(*)) as null_rate from acct_wt_user_client_income where interval_type=2 union
select '客户盈亏金额（近半年）' as name, count(client_income) as tag_num, count(*) as total_num, (1-count(client_income)/count(*)) as null_rate from acct_wt_user_client_income where interval_type=3 union
select '客户盈亏金额（近一年）' as name, count(client_income) as tag_num, count(*) as total_num, (1-count(client_income)/count(*)) as null_rate from acct_wt_user_client_income where interval_type=4 union
select '客户总收益率' as name, count(client_day_income_ratio) as tag_num, count(*) as total_num, (1-count(client_day_income_ratio)/count(*)) as null_rate from acct_wt_user_client_day_income_ratio union
select '客户总收益率（近一月）' as name, count(client_income_ratio) as tag_num, count(*) as total_num, (1-count(client_income_ratio)/count(*)) as null_rate from acct_wt_user_client_income_ratio where interval_type=1 union
select '客户总收益率（近三月）' as name, count(client_income_ratio) as tag_num, count(*) as total_num, (1-count(client_income_ratio)/count(*)) as null_rate from acct_wt_user_client_income_ratio where interval_type=2 union
select '客户总收益率（近半年）' as name, count(client_income_ratio) as tag_num, count(*) as total_num, (1-count(client_income_ratio)/count(*)) as null_rate from acct_wt_user_client_income_ratio where interval_type=3 union
select '客户总收益率（近一年）' as name, count(client_income_ratio) as tag_num, count(*) as total_num, (1-count(client_income_ratio)/count(*)) as null_rate from acct_wt_user_client_income_ratio where interval_type=4 union
select '客户仓位' as name, count(client_position) as tag_num, count(*) as total_num, (1-count(client_position)/count(*)) as null_rate from acct_wt_user_client_position union
select '客户仓位（近一月）' as name, count(client_avg_position) as tag_num, count(*) as total_num, (1-count(client_avg_position)/count(*)) as null_rate from acct_wt_user_client_avg_position where interval_type=1 union
select '客户仓位（近三月）' as name, count(client_avg_position) as tag_num, count(*) as total_num, (1-count(client_avg_position)/count(*)) as null_rate from acct_wt_user_client_avg_position where interval_type=2 union
select '客户仓位（近半年）' as name, count(client_avg_position) as tag_num, count(*) as total_num, (1-count(client_avg_position)/count(*)) as null_rate from acct_wt_user_client_avg_position where interval_type=3 union
select '客户仓位（近一年）' as name, count(client_avg_position) as tag_num, count(*) as total_num, (1-count(client_avg_position)/count(*)) as null_rate from acct_wt_user_client_avg_position where interval_type=4 union
select '投资品种偏好' as name, count(preference_type) as tag_num, count(*) as total_num, (1-count(preference_type)/count(*)) as null_rate from acct_wt_user_investment_preference union
select '净赚最多股票（近一周）' as name, count(stock_income_balance) as tag_num, count(*) as total_num, (1-count(stock_income_balance)/count(*)) as null_rate from acct_wt_user_max_profit_stock union
select '净赚最多股票（近一月）' as name, count(stock_income_balance) as tag_num, count(*) as total_num, (1-count(stock_income_balance)/count(*)) as null_rate from acct_wt_user_max_profit_stock where interval_type=1 union
select '净赚最多股票（近三月）' as name, count(stock_income_balance) as tag_num, count(*) as total_num, (1-count(stock_income_balance)/count(*)) as null_rate from acct_wt_user_max_profit_stock where interval_type=2 union
select '净赚最多股票（近半年）' as name, count(stock_income_balance) as tag_num, count(*) as total_num, (1-count(stock_income_balance)/count(*)) as null_rate from acct_wt_user_max_profit_stock where interval_type=3 union
select '净赚最多股票（近一年）' as name, count(stock_income_balance) as tag_num, count(*) as total_num, (1-count(stock_income_balance)/count(*)) as null_rate from acct_wt_user_max_profit_stock where interval_type=4 union
select '亏损最多股票（近一周）' as name, count(stock_income_balance) as tag_num, count(*) as total_num, (1-count(stock_income_balance)/count(*)) as null_rate from acct_wt_user_max_loss_stock union
select '亏损最多股票（近一月）' as name, count(stock_income_balance) as tag_num, count(*) as total_num, (1-count(stock_income_balance)/count(*)) as null_rate from acct_wt_user_max_loss_stock where interval_type=1 union
select '亏损最多股票（近三月）' as name, count(stock_income_balance) as tag_num, count(*) as total_num, (1-count(stock_income_balance)/count(*)) as null_rate from acct_wt_user_max_loss_stock where interval_type=2 union
select '亏损最多股票（近半年）' as name, count(stock_income_balance) as tag_num, count(*) as total_num, (1-count(stock_income_balance)/count(*)) as null_rate from acct_wt_user_max_loss_stock where interval_type=3 union
select '亏损最多股票（近一年）' as name, count(stock_income_balance) as tag_num, count(*) as total_num, (1-count(stock_income_balance)/count(*)) as null_rate from acct_wt_user_max_loss_stock where interval_type=4 union
select '普通账户收益率（近一月）' as name, count(last_month_income_ratio) as tag_num, count(*) as total_num, (1-count(last_month_income_ratio)/count(*)) as null_rate from acct_wt_user_last_month_income_ratio where interval_type=1 union
select '普通账户收益率（近三月）' as name, count(last_quarter_income_ratio) as tag_num, count(*) as total_num, (1-count(last_quarter_income_ratio)/count(*)) as null_rate from acct_wt_user_last_quarter_income_ratio where interval_type=2 union
select '普通账户收益率（近半年）' as name, count(last_halfyear_income_ratio) as tag_num, count(*) as total_num, (1-count(last_halfyear_income_ratio)/count(*)) as null_rate from acct_wt_user_last_halfyear_income_ratio where interval_type=3 union
select '普通账户收益率（近一年）' as name, count(last_year_income_ratio) as tag_num, count(*) as total_num, (1-count(last_year_income_ratio)/count(*)) as null_rate from acct_wt_user_last_year_income_ratio where interval_type=4 union
select '期权账户总资产' as name, count(opt_total_asset) as tag_num, count(*) as total_num, (1-count(opt_total_asset)/count(*)) as null_rate from acct_wt_user_opt_day_asset union
select '普通账户盈亏额（近一月）' as name, count(total_income_balance) as tag_num, count(*) as total_num, (1-count(total_income_balance)/count(*)) as null_rate from acct_wt_user_account_income_balance where interval_type=1 union
select '普通账户盈亏额（近三月）' as name, count(total_income_balance) as tag_num, count(*) as total_num, (1-count(total_income_balance)/count(*)) as null_rate from acct_wt_user_account_income_balance where interval_type=2 union
select '普通账户盈亏额（近半年）' as name, count(total_income_balance) as tag_num, count(*) as total_num, (1-count(total_income_balance)/count(*)) as null_rate from acct_wt_user_account_income_balance where interval_type=3 union
select '普通账户盈亏额（近一年）' as name, count(total_income_balance) as tag_num, count(*) as total_num, (1-count(total_income_balance)/count(*)) as null_rate from acct_wt_user_account_income_balance where interval_type=4 union
select '信用账户盈亏额（近一月）' as name, count(credit_income) as tag_num, count(*) as total_num, (1-count(credit_income)/count(*)) as null_rate from acct_wt_user_credit_income where interval_type=1 union
select '信用账户盈亏额（近三月）' as name, count(credit_income) as tag_num, count(*) as total_num, (1-count(credit_income)/count(*)) as null_rate from acct_wt_user_credit_income where interval_type=2 union
select '信用账户盈亏额（近半年）' as name, count(credit_income) as tag_num, count(*) as total_num, (1-count(credit_income)/count(*)) as null_rate from acct_wt_user_credit_income where interval_type=3 union
select '信用账户盈亏额（近一年）' as name, count(credit_income) as tag_num, count(*) as total_num, (1-count(credit_income)/count(*)) as null_rate from acct_wt_user_credit_income where interval_type=4 union
select '期权账户盈亏额（近一月）' as name, count(opt_total_income) as tag_num, count(*) as total_num, (1-count(opt_total_income)/count(*)) as null_rate from acct_wt_user_opt_total_income where interval_type=1 union
select '期权账户盈亏额（近三月）' as name, count(opt_total_income) as tag_num, count(*) as total_num, (1-count(opt_total_income)/count(*)) as null_rate from acct_wt_user_opt_total_income where interval_type=2 union
select '期权账户盈亏额（近半年）' as name, count(opt_total_income) as tag_num, count(*) as total_num, (1-count(opt_total_income)/count(*)) as null_rate from acct_wt_user_opt_total_income where interval_type=3 union
select '期权账户盈亏额（近一年）' as name, count(opt_total_income) as tag_num, count(*) as total_num, (1-count(opt_total_income)/count(*)) as null_rate from acct_wt_user_opt_total_income where interval_type=4 union
select '理财产品总市值' as name, count(prod_market_value) as tag_num, count(*) as total_num, (1-count(prod_market_value)/count(*)) as null_rate from acct_wt_user_prod_market_value union
select '客户转入金额（近一月）' as name, count(in_balance) as tag_num, count(*) as total_num, (1-count(in_balance)/count(*)) as null_rate from acct_wt_user_client_in_out_balance where interval_type=1 union
select '客户转入金额（近三月）' as name, count(in_balance) as tag_num, count(*) as total_num, (1-count(in_balance)/count(*)) as null_rate from acct_wt_user_client_in_out_balance where interval_type=2 union
select '客户转入金额（近半年）' as name, count(in_balance) as tag_num, count(*) as total_num, (1-count(in_balance)/count(*)) as null_rate from acct_wt_user_client_in_out_balance where interval_type=3 union
select '客户转入金额（近一年）' as name, count(in_balance) as tag_num, count(*) as total_num, (1-count(in_balance)/count(*)) as null_rate from acct_wt_user_client_in_out_balance where interval_type=4 union
select '客户转出金额（近一月）' as name, count(out_balance) as tag_num, count(*) as total_num, (1-count(out_balance)/count(*)) as null_rate from acct_wt_user_client_in_out_balance where interval_type=1 union
select '客户转出金额（近三月）' as name, count(out_balance) as tag_num, count(*) as total_num, (1-count(out_balance)/count(*)) as null_rate from acct_wt_user_client_in_out_balance where interval_type=2 union
select '客户转出金额（近半年）' as name, count(out_balance) as tag_num, count(*) as total_num, (1-count(out_balance)/count(*)) as null_rate from acct_wt_user_client_in_out_balance where interval_type=3 union
select '客户转出金额（近一年）' as name, count(out_balance) as tag_num, count(*) as total_num, (1-count(out_balance)/count(*)) as null_rate from acct_wt_user_client_in_out_balance where interval_type=4 union
select '客户资金余额' as name, count(client_current_balance) as tag_num, count(*) as total_num, (1-count(client_current_balance)/count(*)) as null_rate from acct_wt_user_client_total_asset union
select '客户日均资金余额（近一月）' as name, count(client_avg_fund_asset) as tag_num, count(*) as total_num, (1-count(client_avg_fund_asset)/count(*)) as null_rate from acct_wt_user_client_avg_total_asset where interval_type=1 union
select '客户日均资金余额（近三月）' as name, count(client_avg_fund_asset) as tag_num, count(*) as total_num, (1-count(client_avg_fund_asset)/count(*)) as null_rate from acct_wt_user_client_avg_total_asset where interval_type=2 union
select '客户日均资金余额（近半年）' as name, count(client_avg_fund_asset) as tag_num, count(*) as total_num, (1-count(client_avg_fund_asset)/count(*)) as null_rate from acct_wt_user_client_avg_total_asset where interval_type=3 union
select '客户日均资金余额（近一年）' as name, count(client_avg_fund_asset) as tag_num, count(*) as total_num, (1-count(client_avg_fund_asset)/count(*)) as null_rate from acct_wt_user_client_avg_total_asset where interval_type=4 union
